  create table users (
        phone_number numeric(38,0),
        created_at timestamp(6),
        updated_at timestamp(6),
        user_id bigint generated by default as identity,
        auth_provider varchar(255) not null check (auth_provider in ('LOCAL','GOOGLE')),
        avatar_url varchar(255),
        email varchar(255) not null unique,
        id_google varchar(255),
        name varchar(255) not null,
        password_hash varchar(255) not null,
        primary key (user_id)
    );