create table groups (
        draw_date date,
        maximum_value numeric(38,2),
        minimum_value numeric(38,2),
        creator_user_id bigint,
        group_id bigint generated by default as identity,
        description TEXT,
        local varchar(255),
        name varchar(255),
        status_group varchar(255) check (status_group in ('CREATE','ACTIVE','COMPLETED','DELETED')),
        primary key (group_id)
    );