create table users_groups (
        entry_date timestamp(6),
        gift_select_id bigint,
        group_id bigint not null,
        recipient_user_id bigint,
        sender_user_id bigint not null,
        updated_at timestamp(6),
        user_group_id bigint generated by default as identity,
        primary key (user_group_id)
    );