create table wish_lists (
        gift_id bigint not null,
        user_group_id bigint not null unique,
        wish_list_id bigint generated by default as identity,
        primary key (wish_list_id)
    );